### ISSUE TITLE
[1.18.2] Mod doesn't work

### ISSUE THREAD

**Issue by BelgianDev** [Cy4Shot/ItemStitchingFix#7]
Hello, I'm using [https://www.curseforge.com/minecraft/mc-mods/rubidium](Rubidium) and I think that's the reason why it does not work

![image](https://user-images.githubusercontent.com/72615320/179420058-aae73e4d-f2ba-434d-af09-da2512956764.png)

**Comment by Cy4Shot** [comment]
Try pressing `i` and switching the method to `PIXEL`.
